### ISSUE TITLE
Parser gives strange error

### ISSUE THREAD

**Issue by SomeRandom4ChanGuy** [Mattias-/ion#3]
First of all I wanted to say that I really enjoyed that blog post of yours. So I tried to run it using this command: ```C:\Users\-------\Desktop\ion>target\ion.exe test\iter1\good\g01.ion```. But it only gives me the following error: ```', C:\Users\-------\Desktop\ion\src\parser.rs:80```.
If you look at line 80:
```rust
panic!("No match: {}", s);
```
I would guess this error relates to some weird \r\n handling, since it should actually output "No match: "

**Comment by Mattias-** [comment]
Thank you!
I created another issue for the line endings in case this is caused by something different.
#4

**Comment by SomeRandom4ChanGuy** [comment]
Changing it to lines_any does the trick. Thanks.
